#!/usr/bin/env python3
"""
Claude Agents 7层体系团队配置脚本
用法: python configure-team.py --stack qt-cpp --project-path .
"""

import argparse
import json
import os
import sys
from pathlib import Path
import subprocess
import datetime


class AgentConfigurator:
    """7层AI团队配置器"""
    
    def __init__(self, project_path: str, stack: str = "auto"):
        self.project_path = Path(project_path).resolve()
        self.stack = stack
        self.agents_config = {}
        
    def detect_stack(self) -> dict:
        """检测项目技术栈"""
        stack_info = {
            "language": [],
            "framework": [],
            "build_system": [],
            "project_type": "unknown"
        }
        
        # 检查C++/Qt
        if (self.project_path / "CMakeLists.txt").exists():
            stack_info["build_system"].append("CMake")
            
            # 读取CMakeLists.txt检测Qt
            cmake_content = (self.project_path / "CMakeLists.txt").read_text(encoding="utf-8", errors="ignore")
            if "Qt" in cmake_content or "qt" in cmake_content.lower():
                stack_info["framework"].append("Qt")
                stack_info["project_type"] = "qt-cpp"
        
        if (self.project_path / "*.pro").glob("*.pro"):
            stack_info["build_system"].append("qmake")
            stack_info["framework"].append("Qt")
            stack_info["project_type"] = "qt-cpp"
            
        # 检查C++文件
        cpp_files = list(self.project_path.rglob("*.cpp")) + list(self.project_path.rglob("*.h"))
        if cpp_files:
            stack_info["language"].append("C++")
            
        # 检查Python
        if (self.project_path / "requirements.txt").exists() or list(self.project_path.rglob("*.py")):
            stack_info["language"].append("Python")
            
        return stack_info
    
    def get_optimal_agents(self, stack_info: dict) -> dict:
        """根据技术栈选择最优agents"""
        agents = {
            "core_team": [
                {"name": "team-configurator", "layer": "role-layer", "mandatory": True},
                {"name": "architect", "layer": "role-layer", "mandatory": True},
                {"name": "auditor", "layer": "role-layer", "mandatory": True}
            ],
            "language_experts": [],
            "framework_specialists": [],
            "component_experts": []
        }
        
        # 语言专家
        if "C++" in stack_info["language"]:
            agents["language_experts"].append({
                "name": "cpp-expert", 
                "layer": "language-layer",
                "use_case": "C++17/20 features, templates, Qt integration"
            })
            
        if "Python" in stack_info["language"]:
            agents["language_experts"].append({
                "name": "python-expert",
                "layer": "language-layer", 
                "use_case": "Scientific computing, automation, Qt bindings"
            })
        
        # Qt专业组件
        if stack_info["project_type"] == "qt-cpp":
            qt_components = [
                {"name": "qt-ui-designer", "use_case": "UI design, layout, styling"},
                {"name": "device-command-tester", "use_case": "Serial communication, protocols"},
                {"name": "ui-tester", "use_case": "Functional UI testing"},
                {"name": "module-tester", "use_case": "Unit and integration testing"}
            ]
            
            for comp in qt_components:
                comp["layer"] = "component-layer"
                agents["component_experts"].append(comp)
                
        return agents
    
    def generate_claude_md_config(self, stack_info: dict, agents: dict) -> str:
        """生成CLAUDE.md配置部分"""
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d")
        
        config = f"""## AI Team Configuration (autogenerated by team-configurator, {timestamp})
**重要: 请使用专业化subagents处理对应任务。**

### 检测到的技术栈
"""
        
        if stack_info["language"]:
            config += f"- 编程语言: {', '.join(stack_info['language'])}\n"
        if stack_info["framework"]:
            config += f"- 框架: {', '.join(stack_info['framework'])}\n"
        if stack_info["build_system"]:
            config += f"- 构建系统: {', '.join(stack_info['build_system'])}\n"
        config += f"- 项目类型: {stack_info['project_type']}\n"
        
        config += """
### 7层Agent团队分配

| 任务类型 | 首选Agent | 层级 | 说明 |
|---------|----------|------|------|
"""
        
        # 核心团队
        for agent in agents["core_team"]:
            if agent["name"] == "architect":
                config += f"| 架构设计 | @{agent['name']} | {agent['layer']} | 系统级设计 |\n"
            elif agent["name"] == "auditor":
                config += f"| 代码审查 | @{agent['name']} | {agent['layer']} | 质量保证 |\n"
        
        # 语言专家
        for agent in agents["language_experts"]:
            lang = "C++" if "cpp" in agent["name"] else "Python"
            config += f"| {lang}开发 | @{agent['name']} | {agent['layer']} | {agent['use_case']} |\n"
        
        # 组件专家
        for agent in agents["component_experts"]:
            task = agent["use_case"].split(",")[0]  # 取第一个用途作为任务名
            config += f"| {task} | @{agent['name']} | {agent['layer']} | {agent['use_case']} |\n"
        
        config += """
### 性能与质量保证
| 任务类型 | 首选Agent | 层级 | 说明 |
|---------|----------|------|------|
| 性能优化 | @performance-optimizer | role-layer | Qt/C++性能调优 |
| 技术研究 | @researcher | role-layer | 新技术调研 |
| 文档生成 | @memory-network-builder | role-layer | 知识图谱构建 |

### 使用示例
```bash
# 架构设计
claude "use @architect and design a device communication module"

# Qt界面开发  
claude "use @qt-ui-designer and create settings dialog with validation"

# 代码审查
claude "use @auditor and review my latest changes"

# 性能优化
claude "use @performance-optimizer and analyze memory usage"
```
"""
        
        return config
    
    def update_claude_md(self, config_content: str) -> bool:
        """更新项目的CLAUDE.md文件"""
        claude_md_path = self.project_path / "CLAUDE.md"
        
        if claude_md_path.exists():
            # 读取现有内容
            existing_content = claude_md_path.read_text(encoding="utf-8", errors="ignore")
            
            # 查找并替换AI Team Configuration部分
            import re
            pattern = r'## AI Team Configuration.*?(?=\n## [^A]|\n# [^A]|$)'
            if re.search(pattern, existing_content, re.DOTALL):
                # 替换现有配置
                new_content = re.sub(pattern, config_content.rstrip(), existing_content, flags=re.DOTALL)
            else:
                # 添加新配置到文件末尾
                new_content = existing_content.rstrip() + "\n\n" + config_content
        else:
            # 创建新的CLAUDE.md
            new_content = f"""# {self.project_path.name}

{config_content}
"""
        
        try:
            claude_md_path.write_text(new_content, encoding="utf-8")
            return True
        except Exception as e:
            print(f"❌ 更新CLAUDE.md失败: {e}")
            return False
    
    def run_configuration(self) -> bool:
        """执行完整配置流程"""
        print(f"🔍 分析项目: {self.project_path}")
        
        # 检测技术栈
        if self.stack == "auto":
            stack_info = self.detect_stack()
        else:
            # 手动指定的技术栈
            stack_info = {"project_type": self.stack, "language": ["C++"], "framework": ["Qt"]}
        
        print(f"📊 检测结果: {stack_info}")
        
        # 选择agents
        agents = self.get_optimal_agents(stack_info)
        print(f"👥 配置团队: {len(agents['core_team']) + len(agents['language_experts']) + len(agents['component_experts'])} agents")
        
        # 生成配置
        config_content = self.generate_claude_md_config(stack_info, agents)
        
        # 更新CLAUDE.md
        success = self.update_claude_md(config_content)
        
        if success:
            print("✅ CLAUDE.md更新成功!")
            print("\n🎯 建议的下一步:")
            print(f"   cd {self.project_path}")
            print('   claude "use @team-configurator and verify the configuration"')
            return True
        else:
            return False


def main():
    parser = argparse.ArgumentParser(description="Claude Agents 7层体系配置工具")
    parser.add_argument("--project-path", default=".", help="项目路径 (默认: 当前目录)")
    parser.add_argument("--stack", default="auto", choices=["auto", "qt-cpp", "python"], 
                       help="技术栈类型 (默认: auto)")
    parser.add_argument("--dry-run", action="store_true", help="只显示配置，不写入文件")
    
    args = parser.parse_args()
    
    print("🚀 Claude Agents 7层体系配置器")
    print("=" * 40)
    
    configurator = AgentConfigurator(args.project_path, args.stack)
    
    if args.dry_run:
        print("🔍 DRY RUN 模式 - 不会修改文件")
        stack_info = configurator.detect_stack()
        agents = configurator.get_optimal_agents(stack_info)
        config = configurator.generate_claude_md_config(stack_info, agents)
        print("\n生成的配置:")
        print("-" * 40)
        print(config)
    else:
        success = configurator.run_configuration()
        sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()